// <auto-generated />
namespace Contry_State_City.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initLoad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initLoad));
        
        string IMigrationMetadata.Id
        {
            get { return "202309121703500_initLoad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
